// types.js

export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_PETS_LIST = 'SET_PETS_LIST';
export const SELECT_PET = 'SELECT_PET';
export const GET_ALL_USERS = 'GET_ALL_USERS';
export const TOTAL_PAGES = 'TOTAL_PAGES';
export const PET_EDIT_SHOW = 'PET_EDIT_SHOW'
export const REQUEST_HELP_PENDING = 'REQUEST_HELP_PENDING'
export const GET_ALL_REQUESTS = 'GET_ALL_REQUESTS'
export const GET_REQUEST_DETAILS = 'GET_REQUEST_DETAILS' 
export const PET_ALL_NOTES = 'PET_ALL_NOTES'
export const PET_NOTE_SHOW = 'PET_NOTE_SHOW'
export const ACCEPTED_CALL_ADMIN = 'ACCEPTED_CALL_ADMIN'
export const USER_EDIT_SHOW = 'USER_EDIT_SHOW'